//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altinoren.ActiveWriter
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "actiw";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"ActiveWriter";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"altinoren.com";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ActiveWriterDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ActiveWriterCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ActiveWriterExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ActiveWriterCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewActiveWriterExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ActiveWriterCommandSetId), 0x0001);
	
		// Package identifier
		public const string ActiveWriterPackageId = "9f4f10d0-81ad-4308-a398-ba7741f3f7e2";
		
		// Editor factory identifier
		public const string ActiveWriterEditorFactoryId = "afa967d1-99df-4330-a1d6-a96343c24786";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ActiveWriterModelExplorerToolWindowId = "762a1a9f-b314-4480-8df1-227a3166ee9c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Altinoren.ActiveWriter
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ActiveWriterCommandSetId = "9928a048-76e7-4f47-8055-2b7da11b6f58";
		public const string ActiveWriterClassDetailsToolWindowId = "1a0d2807-900b-4092-9ac9-1829dd34ce6f";
		public static readonly global::System.ComponentModel.Design.CommandID ViewClassDetailsCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ActiveWriterCommandSetId), 0x10002);
	}
}