//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.MonoRail.ViewComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Castle.MonoRail.ViewComponents.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery(function() {(function($)
        ///{       $(&quot;.collapsed&quot;).click(function(evnt)  
        ///        { var chld = $(this).children(&quot;ul&quot;);  
        ///           if (chld.length &gt; 0) 
        ///           { 
        ///              chld.toggle(&quot;normal&quot;); return false; 
        ///          } 
        ///        }).children(&quot;ul&quot;).hide();
        ///        $(&quot;.collapsed a&quot;).click(function(evnt) { evnt.stopPropagation(); });
        ///})(jQuery); }).
        /// </summary>
        public static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.observe(window, &apos;load&apos;, function()
        ///{   $$(&quot;.collapsed&quot;).each(function(elem)
        ///    {   Event.observe(elem, &quot;click&quot;, function(evnt)
        ///        {    new Effect.toggle(this.getElementsBySelector(&quot;ul&quot;).first(), &quot;slide&quot;);
        ///            Event.stop(evnt);
        ///        } .bindAsEventListener(elem));
        ///        elem.getElementsBySelector(&quot;ul&quot;).first().hide();
        ///    });
        ///    $$(&quot;.collapsed a&quot;).each(function(elem) { Event.observe(elem, &quot;click&quot;, function(evnt) {Event.stop(evnt); }); });
        ///});.
        /// </summary>
        public static string prototype {
            get {
                return ResourceManager.GetString("prototype", resourceCulture);
            }
        }
    }
}
