 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debugging.Tests {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class SimpleGenericClass : ActiveRecordBase<SimpleGenericClass> {
    }
    
    [ActiveRecord()]
    public partial class ExplicitGenericClassInGenericModel : ActiveRecordBase<ExplicitGenericClassInGenericModel> {
    }
    
    [ActiveRecord()]
    public partial class ExplicitNonGenericClassInGenericModel : ActiveRecordBase {
    }
    
    [ActiveRecord()]
    public partial class ExplicitGenericRelationDecleration_HasMany : ActiveRecordBase<ExplicitGenericRelationDecleration_HasMany> {
        
        private IDictionary<string, ExplicitGenericRelationDecleration_BelongsTo> _explicitGenericRelationDecleration_BelongsToes;
        
        [HasMany(typeof(ExplicitGenericRelationDecleration_BelongsTo), ColumnKey="ExplicitGenericRelationDecleration_HasMany", RelationType=RelationType.Map, IndexType="string", Index="Handle")]
        public IDictionary<string, ExplicitGenericRelationDecleration_BelongsTo> ExplicitGenericRelationDecleration_BelongsToes {
            get {
                return this._explicitGenericRelationDecleration_BelongsToes;
            }
            set {
                this._explicitGenericRelationDecleration_BelongsToes = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class ExplicitGenericRelationDecleration_BelongsTo : ActiveRecordBase<ExplicitGenericRelationDecleration_BelongsTo> {
        
        private ExplicitGenericRelationDecleration_HasMany _explicitGenericRelationDecleration_HasMany;
        
        [BelongsTo()]
        public ExplicitGenericRelationDecleration_HasMany ExplicitGenericRelationDecleration_HasMany {
            get {
                return this._explicitGenericRelationDecleration_HasMany;
            }
            set {
                this._explicitGenericRelationDecleration_HasMany = value;
            }
        }
    }
    
    public class GeneratedCodeGenericTestModelHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(SimpleGenericClass),
                    typeof(ExplicitGenericClassInGenericModel),
                    typeof(ExplicitNonGenericClassInGenericModel),
                    typeof(ExplicitGenericRelationDecleration_HasMany),
                    typeof(ExplicitGenericRelationDecleration_BelongsTo)};
        }
    }
}
