//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debugging.Tests {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class SimpleGenericClass : ActiveRecordBase<SimpleGenericClass> {
    }
    
    [ActiveRecord()]
    public partial class ExplicitGenericClassInGenericModel : ActiveRecordBase<ExplicitGenericClassInGenericModel> {
    }
    
    [ActiveRecord()]
    public partial class ExplicitNonGenericClassInGenericModel : ActiveRecordBase {
    }
}
