//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debugging.Tests {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class InClassMetaDataType : ActiveRecordBase<InClassMetaDataType> {
        
        private string _myPK;
        
        [Field(ColumnType="String", Access=PropertyAccess.Field)]
        public string MyField;
        
        private string _myProperty;
        
        private int _myVersion;
        
        private int _myTimestamp;
        
        public static string MyPKProperty = "MyPK";
        
        public static string MyFieldProperty = "MyField";
        
        public static string MyPropertyProperty = "MyProperty";
        
        public static string MyVersionProperty = "MyVersion";
        
        public static string MyTimestampProperty = "MyTimestamp";
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="String")]
        public virtual string MyPK {
            get {
                return this._myPK;
            }
            set {
                this._myPK = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string MyProperty {
            get {
                return this._myProperty;
            }
            set {
                this._myProperty = value;
            }
        }
        
        [Version(Type="Int32")]
        public virtual int MyVersion {
            get {
                return this._myVersion;
            }
            set {
                this._myVersion = value;
            }
        }
        
        [Timestamp()]
        public virtual int MyTimestamp {
            get {
                return this._myTimestamp;
            }
            set {
                this._myTimestamp = value;
            }
        }
    }
}
