//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainModel ActiveWriterDomainModel
	/// A Visual Studio 2005 addin to design domain models and to generate code
	/// decorated with ActiveRecord attributes based on the model.
	/// </summary>
	[DslDesign::DisplayNameResource("Altinoren.ActiveWriter.ActiveWriterDomainModel.DisplayName", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Altinoren.ActiveWriter.ActiveWriterDomainModel.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("3a7d8d12-f07c-4dd1-8689-f9610e7a79e1")]
	public partial class ActiveWriterDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// ActiveWriterDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x3a7d8d12, 0xf07c, 0x4dd1, 0x86, 0x89, 0xf9, 0x61, 0x0e, 0x7a, 0x79, 0xe1);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public ActiveWriterDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
		}
		
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Model),
				typeof(ModelClass),
				typeof(ModelProperty),
				typeof(ModelElementWithAccess),
				typeof(NamedElement),
				typeof(NestedClass),
				typeof(ModelHasClass),
				typeof(ManyToOneRelation),
				typeof(ClassHasProperty),
				typeof(ManyToManyRelation),
				typeof(OneToOneRelation),
				typeof(ModelHasNestedClasses),
				typeof(NestedClassHasProperties),
				typeof(NestedClassReferencesModelClasses),
				typeof(ActiveRecordMapping),
				typeof(ManyToOneConnector),
				typeof(ManyToManyConnector),
				typeof(OneToOneConnector),
				typeof(NestedConnector),
				typeof(ClassShape),
				typeof(NestedClassShape),
				typeof(global::Altinoren.ActiveWriter.FixUpDiagram),
				typeof(global::Altinoren.ActiveWriter.ConnectorRolePlayerChanged),
				typeof(global::Altinoren.ActiveWriter.CompartmentItemAddRule),
				typeof(global::Altinoren.ActiveWriter.CompartmentItemDeleteRule),
				typeof(global::Altinoren.ActiveWriter.CompartmentItemRolePlayerChangeRule),
				typeof(global::Altinoren.ActiveWriter.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::Altinoren.ActiveWriter.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Model), "UseNullables", Model.UseNullablesDomainPropertyId, typeof(Model.UseNullablesPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "CaseOfPrivateFields", Model.CaseOfPrivateFieldsDomainPropertyId, typeof(Model.CaseOfPrivateFieldsPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "GenerateMonoRailProject", Model.GenerateMonoRailProjectDomainPropertyId, typeof(Model.GenerateMonoRailProjectPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "MonoRailProjectName", Model.MonoRailProjectNameDomainPropertyId, typeof(Model.MonoRailProjectNamePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "MonoRailProjectPath", Model.MonoRailProjectPathDomainPropertyId, typeof(Model.MonoRailProjectPathPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "MonoRailDefaultLayout", Model.MonoRailDefaultLayoutDomainPropertyId, typeof(Model.MonoRailDefaultLayoutPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "MonoRailDefaultRescue", Model.MonoRailDefaultRescueDomainPropertyId, typeof(Model.MonoRailDefaultRescuePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "MonoRailViewFileExtension", Model.MonoRailViewFileExtensionDomainPropertyId, typeof(Model.MonoRailViewFileExtensionPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "UseGenerics", Model.UseGenericsDomainPropertyId, typeof(Model.UseGenericsPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "UseBaseClass", Model.UseBaseClassDomainPropertyId, typeof(Model.UseBaseClassPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "BaseClassName", Model.BaseClassNameDomainPropertyId, typeof(Model.BaseClassNamePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "GeneratesDoubleDerived", Model.GeneratesDoubleDerivedDomainPropertyId, typeof(Model.GeneratesDoubleDerivedPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "DoubleDerivedNameSuffix", Model.DoubleDerivedNameSuffixDomainPropertyId, typeof(Model.DoubleDerivedNameSuffixPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "UseGeneratedCodeAttribute", Model.UseGeneratedCodeAttributeDomainPropertyId, typeof(Model.UseGeneratedCodeAttributePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "Target", Model.TargetDomainPropertyId, typeof(Model.TargetPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "AssemblyPath", Model.AssemblyPathDomainPropertyId, typeof(Model.AssemblyPathPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "ActiveRecordAssemblyName", Model.ActiveRecordAssemblyNameDomainPropertyId, typeof(Model.ActiveRecordAssemblyNamePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "NHibernateAssemblyName", Model.NHibernateAssemblyNameDomainPropertyId, typeof(Model.NHibernateAssemblyNamePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "RelateWithActiwFile", Model.RelateWithActiwFileDomainPropertyId, typeof(Model.RelateWithActiwFilePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "UseVirtualProperties", Model.UseVirtualPropertiesDomainPropertyId, typeof(Model.UseVirtualPropertiesPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "Namespace", Model.NamespaceDomainPropertyId, typeof(Model.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "AdditionalImports", Model.AdditionalImportsDomainPropertyId, typeof(Model.AdditionalImportsPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "ImplementINotifyPropertyChanged", Model.ImplementINotifyPropertyChangedDomainPropertyId, typeof(Model.ImplementINotifyPropertyChangedPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "GenerateMetaData", Model.GenerateMetaDataDomainPropertyId, typeof(Model.GenerateMetaDataPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "UseNHQG", Model.UseNHQGDomainPropertyId, typeof(Model.UseNHQGPropertyHandler)),
				new DomainMemberInfo(typeof(Model), "NHQGExecutable", Model.NHQGExecutableDomainPropertyId, typeof(Model.NHQGExecutablePropertyHandler)),
				new DomainMemberInfo(typeof(Model), "UseGenericRelations", Model.UseGenericRelationsDomainPropertyId, typeof(Model.UseGenericRelationsPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Cache", ModelClass.CacheDomainPropertyId, typeof(ModelClass.CachePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "DiscriminatorColumn", ModelClass.DiscriminatorColumnDomainPropertyId, typeof(ModelClass.DiscriminatorColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "DiscriminatorType", ModelClass.DiscriminatorTypeDomainPropertyId, typeof(ModelClass.DiscriminatorTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "DiscriminatorValue", ModelClass.DiscriminatorValueDomainPropertyId, typeof(ModelClass.DiscriminatorValuePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Lazy", ModelClass.LazyDomainPropertyId, typeof(ModelClass.LazyPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Proxy", ModelClass.ProxyDomainPropertyId, typeof(ModelClass.ProxyPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Schema", ModelClass.SchemaDomainPropertyId, typeof(ModelClass.SchemaPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Table", ModelClass.TableDomainPropertyId, typeof(ModelClass.TablePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Where", ModelClass.WhereDomainPropertyId, typeof(ModelClass.WherePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "HasKeyProperty", ModelClass.HasKeyPropertyDomainPropertyId, typeof(ModelClass.HasKeyPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "IsValidatorSet", ModelClass.IsValidatorSetDomainPropertyId, typeof(ModelClass.IsValidatorSetPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "DynamicInsert", ModelClass.DynamicInsertDomainPropertyId, typeof(ModelClass.DynamicInsertPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "DynamicUpdate", ModelClass.DynamicUpdateDomainPropertyId, typeof(ModelClass.DynamicUpdatePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Persister", ModelClass.PersisterDomainPropertyId, typeof(ModelClass.PersisterPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "SelectBeforeUpdate", ModelClass.SelectBeforeUpdateDomainPropertyId, typeof(ModelClass.SelectBeforeUpdatePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Polymorphism", ModelClass.PolymorphismDomainPropertyId, typeof(ModelClass.PolymorphismPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Mutable", ModelClass.MutableDomainPropertyId, typeof(ModelClass.MutablePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "BatchSize", ModelClass.BatchSizeDomainPropertyId, typeof(ModelClass.BatchSizePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "Locking", ModelClass.LockingDomainPropertyId, typeof(ModelClass.LockingPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "UseAutoImport", ModelClass.UseAutoImportDomainPropertyId, typeof(ModelClass.UseAutoImportPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "BaseClassName", ModelClass.BaseClassNameDomainPropertyId, typeof(ModelClass.BaseClassNamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "UseGenerics", ModelClass.UseGenericsDomainPropertyId, typeof(ModelClass.UseGenericsPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "ImplementINotifyPropertyChanged", ModelClass.ImplementINotifyPropertyChangedDomainPropertyId, typeof(ModelClass.ImplementINotifyPropertyChangedPropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "UseGenericRelations", ModelClass.UseGenericRelationsDomainPropertyId, typeof(ModelClass.UseGenericRelationsPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Column", ModelProperty.ColumnDomainPropertyId, typeof(ModelProperty.ColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "ColumnType", ModelProperty.ColumnTypeDomainPropertyId, typeof(ModelProperty.ColumnTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "CustomColumnType", ModelProperty.CustomColumnTypeDomainPropertyId, typeof(ModelProperty.CustomColumnTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "CustomMemberType", ModelProperty.CustomMemberTypeDomainPropertyId, typeof(ModelProperty.CustomMemberTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Formula", ModelProperty.FormulaDomainPropertyId, typeof(ModelProperty.FormulaPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Insert", ModelProperty.InsertDomainPropertyId, typeof(ModelProperty.InsertPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Length", ModelProperty.LengthDomainPropertyId, typeof(ModelProperty.LengthPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "NotNull", ModelProperty.NotNullDomainPropertyId, typeof(ModelProperty.NotNullPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Unique", ModelProperty.UniqueDomainPropertyId, typeof(ModelProperty.UniquePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "UnsavedValue", ModelProperty.UnsavedValueDomainPropertyId, typeof(ModelProperty.UnsavedValuePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Update", ModelProperty.UpdateDomainPropertyId, typeof(ModelProperty.UpdatePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Generator", ModelProperty.GeneratorDomainPropertyId, typeof(ModelProperty.GeneratorPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "KeyType", ModelProperty.KeyTypeDomainPropertyId, typeof(ModelProperty.KeyTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Params", ModelProperty.ParamsDomainPropertyId, typeof(ModelProperty.ParamsPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "SequenceName", ModelProperty.SequenceNameDomainPropertyId, typeof(ModelProperty.SequenceNamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Accessor", ModelProperty.AccessorDomainPropertyId, typeof(ModelProperty.AccessorPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "CompositeKeyName", ModelProperty.CompositeKeyNameDomainPropertyId, typeof(ModelProperty.CompositeKeyNamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "PropertyType", ModelProperty.PropertyTypeDomainPropertyId, typeof(ModelProperty.PropertyTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "DebuggerDisplay", ModelProperty.DebuggerDisplayDomainPropertyId, typeof(ModelProperty.DebuggerDisplayPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Validator", ModelProperty.ValidatorDomainPropertyId, typeof(ModelProperty.ValidatorPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "UniqueKey", ModelProperty.UniqueKeyDomainPropertyId, typeof(ModelProperty.UniqueKeyPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Index", ModelProperty.IndexDomainPropertyId, typeof(ModelProperty.IndexPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "SqlType", ModelProperty.SqlTypeDomainPropertyId, typeof(ModelProperty.SqlTypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "Check", ModelProperty.CheckDomainPropertyId, typeof(ModelProperty.CheckPropertyHandler)),
				new DomainMemberInfo(typeof(ModelProperty), "DefaultMember", ModelProperty.DefaultMemberDomainPropertyId, typeof(ModelProperty.DefaultMemberPropertyHandler)),
				new DomainMemberInfo(typeof(ModelElementWithAccess), "CustomAccess", ModelElementWithAccess.CustomAccessDomainPropertyId, typeof(ModelElementWithAccess.CustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ModelElementWithAccess), "Access", ModelElementWithAccess.AccessDomainPropertyId, typeof(ModelElementWithAccess.AccessPropertyHandler)),
				new DomainMemberInfo(typeof(NamedElement), "Name", NamedElement.NameDomainPropertyId, typeof(NamedElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(NamedElement), "Description", NamedElement.DescriptionDomainPropertyId, typeof(NamedElement.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(NestedClass), "ImplementINotifyPropertyChanged", NestedClass.ImplementINotifyPropertyChangedDomainPropertyId, typeof(NestedClass.ImplementINotifyPropertyChangedPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetCache", ManyToOneRelation.TargetCacheDomainPropertyId, typeof(ManyToOneRelation.TargetCachePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetCascade", ManyToOneRelation.TargetCascadeDomainPropertyId, typeof(ManyToOneRelation.TargetCascadePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetColumnKey", ManyToOneRelation.TargetColumnKeyDomainPropertyId, typeof(ManyToOneRelation.TargetColumnKeyPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetCustomAccess", ManyToOneRelation.TargetCustomAccessDomainPropertyId, typeof(ManyToOneRelation.TargetCustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetInverse", ManyToOneRelation.TargetInverseDomainPropertyId, typeof(ManyToOneRelation.TargetInversePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetLazy", ManyToOneRelation.TargetLazyDomainPropertyId, typeof(ManyToOneRelation.TargetLazyPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetMapType", ManyToOneRelation.TargetMapTypeDomainPropertyId, typeof(ManyToOneRelation.TargetMapTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetOrderBy", ManyToOneRelation.TargetOrderByDomainPropertyId, typeof(ManyToOneRelation.TargetOrderByPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetRelationType", ManyToOneRelation.TargetRelationTypeDomainPropertyId, typeof(ManyToOneRelation.TargetRelationTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetSchema", ManyToOneRelation.TargetSchemaDomainPropertyId, typeof(ManyToOneRelation.TargetSchemaPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetSort", ManyToOneRelation.TargetSortDomainPropertyId, typeof(ManyToOneRelation.TargetSortPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetTable", ManyToOneRelation.TargetTableDomainPropertyId, typeof(ManyToOneRelation.TargetTablePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetWhere", ManyToOneRelation.TargetWhereDomainPropertyId, typeof(ManyToOneRelation.TargetWherePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetDescription", ManyToOneRelation.TargetDescriptionDomainPropertyId, typeof(ManyToOneRelation.TargetDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetPropertyName", ManyToOneRelation.TargetPropertyNameDomainPropertyId, typeof(ManyToOneRelation.TargetPropertyNamePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetPropertyType", ManyToOneRelation.TargetPropertyTypeDomainPropertyId, typeof(ManyToOneRelation.TargetPropertyTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceCascade", ManyToOneRelation.SourceCascadeDomainPropertyId, typeof(ManyToOneRelation.SourceCascadePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceColumn", ManyToOneRelation.SourceColumnDomainPropertyId, typeof(ManyToOneRelation.SourceColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceCustomAccess", ManyToOneRelation.SourceCustomAccessDomainPropertyId, typeof(ManyToOneRelation.SourceCustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceInsert", ManyToOneRelation.SourceInsertDomainPropertyId, typeof(ManyToOneRelation.SourceInsertPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceNotNull", ManyToOneRelation.SourceNotNullDomainPropertyId, typeof(ManyToOneRelation.SourceNotNullPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceOuterJoin", ManyToOneRelation.SourceOuterJoinDomainPropertyId, typeof(ManyToOneRelation.SourceOuterJoinPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceType", ManyToOneRelation.SourceTypeDomainPropertyId, typeof(ManyToOneRelation.SourceTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceUnique", ManyToOneRelation.SourceUniqueDomainPropertyId, typeof(ManyToOneRelation.SourceUniquePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceUpdate", ManyToOneRelation.SourceUpdateDomainPropertyId, typeof(ManyToOneRelation.SourceUpdatePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceDescription", ManyToOneRelation.SourceDescriptionDomainPropertyId, typeof(ManyToOneRelation.SourceDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetAccess", ManyToOneRelation.TargetAccessDomainPropertyId, typeof(ManyToOneRelation.TargetAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourcePropertyName", ManyToOneRelation.SourcePropertyNameDomainPropertyId, typeof(ManyToOneRelation.SourcePropertyNamePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "SourceNotFoundBehaviour", ManyToOneRelation.SourceNotFoundBehaviourDomainPropertyId, typeof(ManyToOneRelation.SourceNotFoundBehaviourPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetNotFoundBehaviour", ManyToOneRelation.TargetNotFoundBehaviourDomainPropertyId, typeof(ManyToOneRelation.TargetNotFoundBehaviourPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetElement", ManyToOneRelation.TargetElementDomainPropertyId, typeof(ManyToOneRelation.TargetElementPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetIndexType", ManyToOneRelation.TargetIndexTypeDomainPropertyId, typeof(ManyToOneRelation.TargetIndexTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetIndex", ManyToOneRelation.TargetIndexDomainPropertyId, typeof(ManyToOneRelation.TargetIndexPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToOneRelation), "TargetFetch", ManyToOneRelation.TargetFetchDomainPropertyId, typeof(ManyToOneRelation.TargetFetchPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceCache", ManyToManyRelation.SourceCacheDomainPropertyId, typeof(ManyToManyRelation.SourceCachePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceCascade", ManyToManyRelation.SourceCascadeDomainPropertyId, typeof(ManyToManyRelation.SourceCascadePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceColumn", ManyToManyRelation.SourceColumnDomainPropertyId, typeof(ManyToManyRelation.SourceColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceCustomAccess", ManyToManyRelation.SourceCustomAccessDomainPropertyId, typeof(ManyToManyRelation.SourceCustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceInverse", ManyToManyRelation.SourceInverseDomainPropertyId, typeof(ManyToManyRelation.SourceInversePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceLazy", ManyToManyRelation.SourceLazyDomainPropertyId, typeof(ManyToManyRelation.SourceLazyPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceMapType", ManyToManyRelation.SourceMapTypeDomainPropertyId, typeof(ManyToManyRelation.SourceMapTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceOrderBy", ManyToManyRelation.SourceOrderByDomainPropertyId, typeof(ManyToManyRelation.SourceOrderByPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceRelationType", ManyToManyRelation.SourceRelationTypeDomainPropertyId, typeof(ManyToManyRelation.SourceRelationTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "Schema", ManyToManyRelation.SchemaDomainPropertyId, typeof(ManyToManyRelation.SchemaPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceSort", ManyToManyRelation.SourceSortDomainPropertyId, typeof(ManyToManyRelation.SourceSortPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "Table", ManyToManyRelation.TableDomainPropertyId, typeof(ManyToManyRelation.TablePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceWhere", ManyToManyRelation.SourceWhereDomainPropertyId, typeof(ManyToManyRelation.SourceWherePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetCache", ManyToManyRelation.TargetCacheDomainPropertyId, typeof(ManyToManyRelation.TargetCachePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetCascade", ManyToManyRelation.TargetCascadeDomainPropertyId, typeof(ManyToManyRelation.TargetCascadePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetColumn", ManyToManyRelation.TargetColumnDomainPropertyId, typeof(ManyToManyRelation.TargetColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetCustomAccess", ManyToManyRelation.TargetCustomAccessDomainPropertyId, typeof(ManyToManyRelation.TargetCustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetInverse", ManyToManyRelation.TargetInverseDomainPropertyId, typeof(ManyToManyRelation.TargetInversePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetLazy", ManyToManyRelation.TargetLazyDomainPropertyId, typeof(ManyToManyRelation.TargetLazyPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetMapType", ManyToManyRelation.TargetMapTypeDomainPropertyId, typeof(ManyToManyRelation.TargetMapTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetOrderBy", ManyToManyRelation.TargetOrderByDomainPropertyId, typeof(ManyToManyRelation.TargetOrderByPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetRelationType", ManyToManyRelation.TargetRelationTypeDomainPropertyId, typeof(ManyToManyRelation.TargetRelationTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetSort", ManyToManyRelation.TargetSortDomainPropertyId, typeof(ManyToManyRelation.TargetSortPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetWhere", ManyToManyRelation.TargetWhereDomainPropertyId, typeof(ManyToManyRelation.TargetWherePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceDescription", ManyToManyRelation.SourceDescriptionDomainPropertyId, typeof(ManyToManyRelation.SourceDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetDescription", ManyToManyRelation.TargetDescriptionDomainPropertyId, typeof(ManyToManyRelation.TargetDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceAccess", ManyToManyRelation.SourceAccessDomainPropertyId, typeof(ManyToManyRelation.SourceAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetAccess", ManyToManyRelation.TargetAccessDomainPropertyId, typeof(ManyToManyRelation.TargetAccessPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourcePropertyType", ManyToManyRelation.SourcePropertyTypeDomainPropertyId, typeof(ManyToManyRelation.SourcePropertyTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetPropertyType", ManyToManyRelation.TargetPropertyTypeDomainPropertyId, typeof(ManyToManyRelation.TargetPropertyTypePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourcePropertyName", ManyToManyRelation.SourcePropertyNameDomainPropertyId, typeof(ManyToManyRelation.SourcePropertyNamePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetPropertyName", ManyToManyRelation.TargetPropertyNameDomainPropertyId, typeof(ManyToManyRelation.TargetPropertyNamePropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "TargetNotFoundBehaviour", ManyToManyRelation.TargetNotFoundBehaviourDomainPropertyId, typeof(ManyToManyRelation.TargetNotFoundBehaviourPropertyHandler)),
				new DomainMemberInfo(typeof(ManyToManyRelation), "SourceNotFoundBehaviour", ManyToManyRelation.SourceNotFoundBehaviourDomainPropertyId, typeof(ManyToManyRelation.SourceNotFoundBehaviourPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "SourceAccess", OneToOneRelation.SourceAccessDomainPropertyId, typeof(OneToOneRelation.SourceAccessPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "SourceCascade", OneToOneRelation.SourceCascadeDomainPropertyId, typeof(OneToOneRelation.SourceCascadePropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "SourceConstrained", OneToOneRelation.SourceConstrainedDomainPropertyId, typeof(OneToOneRelation.SourceConstrainedPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "SourceCustomAccess", OneToOneRelation.SourceCustomAccessDomainPropertyId, typeof(OneToOneRelation.SourceCustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "SourceOuterJoin", OneToOneRelation.SourceOuterJoinDomainPropertyId, typeof(OneToOneRelation.SourceOuterJoinPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "TargetAccess", OneToOneRelation.TargetAccessDomainPropertyId, typeof(OneToOneRelation.TargetAccessPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "TargetCascade", OneToOneRelation.TargetCascadeDomainPropertyId, typeof(OneToOneRelation.TargetCascadePropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "TargetConstrained", OneToOneRelation.TargetConstrainedDomainPropertyId, typeof(OneToOneRelation.TargetConstrainedPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "TargetCustomAccess", OneToOneRelation.TargetCustomAccessDomainPropertyId, typeof(OneToOneRelation.TargetCustomAccessPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "TargetOuterJoin", OneToOneRelation.TargetOuterJoinDomainPropertyId, typeof(OneToOneRelation.TargetOuterJoinPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "SourceDescription", OneToOneRelation.SourceDescriptionDomainPropertyId, typeof(OneToOneRelation.SourceDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "TargetDescription", OneToOneRelation.TargetDescriptionDomainPropertyId, typeof(OneToOneRelation.TargetDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(OneToOneRelation), "Lazy", OneToOneRelation.LazyDomainPropertyId, typeof(OneToOneRelation.LazyPropertyHandler)),
				new DomainMemberInfo(typeof(NestedClassReferencesModelClasses), "MapType", NestedClassReferencesModelClasses.MapTypeDomainPropertyId, typeof(NestedClassReferencesModelClasses.MapTypePropertyHandler)),
				new DomainMemberInfo(typeof(NestedClassReferencesModelClasses), "Insert", NestedClassReferencesModelClasses.InsertDomainPropertyId, typeof(NestedClassReferencesModelClasses.InsertPropertyHandler)),
				new DomainMemberInfo(typeof(NestedClassReferencesModelClasses), "Update", NestedClassReferencesModelClasses.UpdateDomainPropertyId, typeof(NestedClassReferencesModelClasses.UpdatePropertyHandler)),
				new DomainMemberInfo(typeof(NestedClassReferencesModelClasses), "ColumnPrefix", NestedClassReferencesModelClasses.ColumnPrefixDomainPropertyId, typeof(NestedClassReferencesModelClasses.ColumnPrefixPropertyHandler)),
				new DomainMemberInfo(typeof(NestedClassReferencesModelClasses), "Description", NestedClassReferencesModelClasses.DescriptionDomainPropertyId, typeof(NestedClassReferencesModelClasses.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(NestedClassReferencesModelClasses), "PropertyName", NestedClassReferencesModelClasses.PropertyNameDomainPropertyId, typeof(NestedClassReferencesModelClasses.PropertyNamePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(ModelHasClass), "Model", ModelHasClass.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelHasClass), "Class", ModelHasClass.ClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(ManyToOneRelation), "Source", ManyToOneRelation.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(ManyToOneRelation), "Target", ManyToOneRelation.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasProperty), "ModelClass", ClassHasProperty.ModelClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasProperty), "Property", ClassHasProperty.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(ManyToManyRelation), "Source", ManyToManyRelation.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(ManyToManyRelation), "Target", ManyToManyRelation.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(OneToOneRelation), "Source", OneToOneRelation.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(OneToOneRelation), "Target", OneToOneRelation.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelHasNestedClasses), "Model", ModelHasNestedClasses.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelHasNestedClasses), "NestedClass", ModelHasNestedClasses.NestedClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(NestedClassHasProperties), "NestedClass", NestedClassHasProperties.NestedClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(NestedClassHasProperties), "Property", NestedClassHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(NestedClassReferencesModelClasses), "NestedClass", NestedClassReferencesModelClasses.NestedClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(NestedClassReferencesModelClasses), "ModelClass", NestedClassReferencesModelClasses.ModelClassDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(13);
				createElementMap.Add(typeof(Model), 0);
				createElementMap.Add(typeof(ModelClass), 1);
				createElementMap.Add(typeof(ModelProperty), 2);
				createElementMap.Add(typeof(NestedClass), 3);
				createElementMap.Add(typeof(ActiveRecordMapping), 4);
				createElementMap.Add(typeof(ManyToOneConnector), 5);
				createElementMap.Add(typeof(ManyToManyConnector), 6);
				createElementMap.Add(typeof(OneToOneConnector), 7);
				createElementMap.Add(typeof(NestedConnector), 8);
				createElementMap.Add(typeof(ClassShape), 9);
				createElementMap.Add(typeof(NestedClassShape), 10);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				throw new global::System.ArgumentException("elementType is not recognized as a type of domain class which belongs to this domain model.");
			}
			switch (index)
			{
				case 0: return new Model(partition, propertyAssignments);
				case 1: return new ModelClass(partition, propertyAssignments);
				case 2: return new ModelProperty(partition, propertyAssignments);
				case 3: return new NestedClass(partition, propertyAssignments);
				case 4: return new ActiveRecordMapping(partition, propertyAssignments);
				case 5: return new ManyToOneConnector(partition, propertyAssignments);
				case 6: return new ManyToManyConnector(partition, propertyAssignments);
				case 7: return new OneToOneConnector(partition, propertyAssignments);
				case 8: return new NestedConnector(partition, propertyAssignments);
				case 9: return new ClassShape(partition, propertyAssignments);
				case 10: return new NestedClassShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementLinkMap.Add(typeof(ModelHasClass), 0);
				createElementLinkMap.Add(typeof(ManyToOneRelation), 1);
				createElementLinkMap.Add(typeof(ClassHasProperty), 2);
				createElementLinkMap.Add(typeof(ManyToManyRelation), 3);
				createElementLinkMap.Add(typeof(OneToOneRelation), 4);
				createElementLinkMap.Add(typeof(ModelHasNestedClasses), 5);
				createElementLinkMap.Add(typeof(NestedClassHasProperties), 6);
				createElementLinkMap.Add(typeof(NestedClassReferencesModelClasses), 7);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				throw new global::System.ArgumentException("elementLinkType is not recognized as a type of domain relationship which belongs to this domain model.");
			}
			switch (index)
			{
				case 0: return new ModelHasClass(partition, roleAssignments, propertyAssignments);
				case 1: return new ManyToOneRelation(partition, roleAssignments, propertyAssignments);
				case 2: return new ClassHasProperty(partition, roleAssignments, propertyAssignments);
				case 3: return new ManyToManyRelation(partition, roleAssignments, propertyAssignments);
				case 4: return new OneToOneRelation(partition, roleAssignments, propertyAssignments);
				case 5: return new ModelHasNestedClasses(partition, roleAssignments, propertyAssignments);
				case 6: return new NestedClassHasProperties(partition, roleAssignments, propertyAssignments);
				case 7: return new NestedClassReferencesModelClasses(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return ActiveWriterDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (ActiveWriterDomainModel.resourceManager == null)
				{
					ActiveWriterDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(ActiveWriterDomainModel).Assembly);
				}
				return ActiveWriterDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return ActiveWriterDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return ActiveWriterDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (ActiveWriterDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new ActiveWriterCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					ActiveWriterDomainModel.copyClosure = copyFilter;
				}
				return ActiveWriterDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (ActiveWriterDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new ActiveWriterDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					ActiveWriterDomainModel.removeClosure = removeFilter;
				}
				return ActiveWriterDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::Altinoren.ActiveWriter.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ActiveWriterDeleteClosure : ActiveWriterDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ActiveWriterDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	public partial class ActiveWriterDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Generic.Dictionary<global::System.Guid, bool> domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public ActiveWriterDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Altinoren.ActiveWriter.ModelHasClass.ClassDomainRoleId, true);
			DomainRoles.Add(global::Altinoren.ActiveWriter.ModelHasNestedClasses.NestedClassDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			return this.DomainRoles.ContainsKey(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Generic.Dictionary<global::System.Guid, bool> DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Generic.Dictionary<global::System.Guid, bool>();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ActiveWriterCopyClosure : ActiveWriterCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ActiveWriterCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	public partial class ActiveWriterCopyClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Generic.Dictionary<global::System.Guid, bool> domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public ActiveWriterCopyClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Altinoren.ActiveWriter.ModelHasNestedClasses.NestedClassDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return this.DomainRoles.ContainsKey(sourceRoleInfo.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			return this.DomainRoles.ContainsKey(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Generic.Dictionary<global::System.Guid, bool> DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Generic.Dictionary<global::System.Guid, bool>();
				}
				return this.domainRoles;
			}
		}
	
	}
	#endregion
		
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: PropertyAccess
	/// Description for Altinoren.ActiveWriter.PropertyAccess
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PropertyAccess
	{
		/// <summary>
		/// Property
		/// Description for Altinoren.ActiveWriter.PropertyAccess.Property
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/Property.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Property,
		/// <summary>
		/// FieldCamelcase
		/// Description for Altinoren.ActiveWriter.PropertyAccess.FieldCamelcase
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/FieldCamelcase.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		FieldCamelcase,
		/// <summary>
		/// FieldCamelcaseUnderscore
		/// Description for Altinoren.ActiveWriter.PropertyAccess.FieldCamelcaseUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/FieldCamelcaseUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		FieldCamelcaseUnderscore,
		/// <summary>
		/// FieldPascalcaseMUnderscore
		/// Description for Altinoren.ActiveWriter.PropertyAccess.FieldPascalcaseMUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/FieldPascalcaseMUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		FieldPascalcaseMUnderscore,
		/// <summary>
		/// FieldLowercaseUnderscore
		/// Description for Altinoren.ActiveWriter.PropertyAccess.FieldLowercaseUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/FieldLowercaseUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		FieldLowercaseUnderscore,
		/// <summary>
		/// NosetterCamelcase
		/// Description for Altinoren.ActiveWriter.PropertyAccess.NosetterCamelcase
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/NosetterCamelcase.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NosetterCamelcase,
		/// <summary>
		/// NosetterCamelcaseUnderscore
		/// Description for
		/// Altinoren.ActiveWriter.PropertyAccess.NosetterCamelcaseUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/NosetterCamelcaseUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NosetterCamelcaseUnderscore,
		/// <summary>
		/// NosetterPascalcaseMUnderscore
		/// Description for
		/// Altinoren.ActiveWriter.PropertyAccess.NosetterPascalcaseMUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/NosetterPascalcaseMUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NosetterPascalcaseMUnderscore,
		/// <summary>
		/// NosetterLowercaseUnderscore
		/// Description for
		/// Altinoren.ActiveWriter.PropertyAccess.NosetterLowercaseUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/NosetterLowercaseUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NosetterLowercaseUnderscore,
		/// <summary>
		/// Field
		/// Description for Altinoren.ActiveWriter.PropertyAccess.Field
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/Field.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Field,
		/// <summary>
		/// NosetterLowercase
		/// Description for Altinoren.ActiveWriter.PropertyAccess.NosetterLowercase
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyAccess/NosetterLowercase.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NosetterLowercase,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: CacheEnum
	/// Description for Altinoren.ActiveWriter.CacheEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum CacheEnum
	{
		/// <summary>
		/// Undefined
		/// Description for Altinoren.ActiveWriter.CacheEnum.Undefined
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CacheEnum/Undefined.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Undefined,
		/// <summary>
		/// ReadOnly
		/// Description for Altinoren.ActiveWriter.CacheEnum.ReadOnly
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CacheEnum/ReadOnly.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		ReadOnly,
		/// <summary>
		/// ReadWrite
		/// Description for Altinoren.ActiveWriter.CacheEnum.ReadWrite
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CacheEnum/ReadWrite.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		ReadWrite,
		/// <summary>
		/// NonStrictReadWrite
		/// Description for Altinoren.ActiveWriter.CacheEnum.NonStrictReadWrite
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CacheEnum/NonStrictReadWrite.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NonStrictReadWrite,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: PrimaryKeyType
	/// Description for Altinoren.ActiveWriter.PrimaryKeyType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PrimaryKeyType
	{
		/// <summary>
		/// None
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.None
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/None.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		None,
		/// <summary>
		/// Identity
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.Identity
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/Identity.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Identity,
		/// <summary>
		/// Sequence
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.Sequence
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/Sequence.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Sequence,
		/// <summary>
		/// HiLo
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.HiLo
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/HiLo.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		HiLo,
		/// <summary>
		/// SeqHiLo
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.SeqHiLo
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/SeqHiLo.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		SeqHiLo,
		/// <summary>
		/// UuidHex
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.UuidHex
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/UuidHex.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		UuidHex,
		/// <summary>
		/// UuidString
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.UuidString
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/UuidString.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		UuidString,
		/// <summary>
		/// Guid
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.Guid
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/Guid.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Guid,
		/// <summary>
		/// GuidComb
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.GuidComb
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/GuidComb.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		GuidComb,
		/// <summary>
		/// Native
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.Native
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/Native.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Native,
		/// <summary>
		/// Assigned
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.Assigned
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/Assigned.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Assigned,
		/// <summary>
		/// Foreign
		/// Description for Altinoren.ActiveWriter.PrimaryKeyType.Foreign
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PrimaryKeyType/Foreign.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Foreign,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: KeyType
	/// Description for Altinoren.ActiveWriter.KeyType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum KeyType
	{
		/// <summary>
		/// None
		/// Description for Altinoren.ActiveWriter.KeyType.None
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.KeyType/None.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		None,
		/// <summary>
		/// PrimaryKey
		/// Description for Altinoren.ActiveWriter.KeyType.PrimaryKey
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.KeyType/PrimaryKey.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		PrimaryKey,
		/// <summary>
		/// CompositeKey
		/// Description for Altinoren.ActiveWriter.KeyType.CompositeKey
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.KeyType/CompositeKey.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		CompositeKey,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: CascadeEnum
	/// Description for Altinoren.ActiveWriter.CascadeEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum CascadeEnum
	{
		/// <summary>
		/// None
		/// Description for Altinoren.ActiveWriter.CascadeEnum.None
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CascadeEnum/None.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		None,
		/// <summary>
		/// All
		/// Description for Altinoren.ActiveWriter.CascadeEnum.All
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CascadeEnum/All.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		All,
		/// <summary>
		/// SaveUpdate
		/// Description for Altinoren.ActiveWriter.CascadeEnum.SaveUpdate
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CascadeEnum/SaveUpdate.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		SaveUpdate,
		/// <summary>
		/// Delete
		/// Description for Altinoren.ActiveWriter.CascadeEnum.Delete
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CascadeEnum/Delete.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Delete,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: OuterJoinEnum
	/// Description for Altinoren.ActiveWriter.OuterJoinEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum OuterJoinEnum
	{
		/// <summary>
		/// Auto
		/// Description for Altinoren.ActiveWriter.OuterJoinEnum.Auto
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OuterJoinEnum/Auto.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Auto,
		/// <summary>
		/// True
		/// Description for Altinoren.ActiveWriter.OuterJoinEnum.True
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OuterJoinEnum/True.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		True,
		/// <summary>
		/// False
		/// Description for Altinoren.ActiveWriter.OuterJoinEnum.False
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OuterJoinEnum/False.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		False,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: RelationType
	/// Description for Altinoren.ActiveWriter.RelationType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum RelationType
	{
		/// <summary>
		/// Guess
		/// Description for Altinoren.ActiveWriter.RelationType.Guess
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.RelationType/Guess.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Guess,
		/// <summary>
		/// Bag
		/// Description for Altinoren.ActiveWriter.RelationType.Bag
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.RelationType/Bag.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Bag,
		/// <summary>
		/// Set
		/// Description for Altinoren.ActiveWriter.RelationType.Set
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.RelationType/Set.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Set,
		/// <summary>
		/// IdBag
		/// Description for Altinoren.ActiveWriter.RelationType.IdBag
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.RelationType/IdBag.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		IdBag,
		/// <summary>
		/// Map
		/// Description for Altinoren.ActiveWriter.RelationType.Map
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.RelationType/Map.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Map,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: NHibernateType
	/// Description for Altinoren.ActiveWriter.NHibernateType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum NHibernateType
	{
		/// <summary>
		/// AnsiChar
		/// Description for Altinoren.ActiveWriter.NHibernateType.AnsiChar
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/AnsiChar.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		AnsiChar,
		/// <summary>
		/// Single
		/// Description for Altinoren.ActiveWriter.NHibernateType.Single
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Single.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Single,
		/// <summary>
		/// AnsiString
		/// Description for Altinoren.ActiveWriter.NHibernateType.AnsiString
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/AnsiString.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		AnsiString,
		/// <summary>
		/// CultureInfo
		/// Description for Altinoren.ActiveWriter.NHibernateType.CultureInfo
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/CultureInfo.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		CultureInfo,
		/// <summary>
		/// Binary
		/// Description for Altinoren.ActiveWriter.NHibernateType.Binary
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Binary.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Binary,
		/// <summary>
		/// Type
		/// Description for Altinoren.ActiveWriter.NHibernateType.Type
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Type.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Type,
		/// <summary>
		/// String
		/// Description for Altinoren.ActiveWriter.NHibernateType.String
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/String.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		String,
		/// <summary>
		/// StringClob
		/// Description for Altinoren.ActiveWriter.NHibernateType.StringClob
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/StringClob.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		StringClob,
		/// <summary>
		/// BinaryBlob
		/// Description for Altinoren.ActiveWriter.NHibernateType.BinaryBlob
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/BinaryBlob.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		BinaryBlob,
		/// <summary>
		/// Boolean
		/// Description for Altinoren.ActiveWriter.NHibernateType.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Boolean.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Boolean,
		/// <summary>
		/// Byte
		/// Description for Altinoren.ActiveWriter.NHibernateType.Byte
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Byte.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Byte,
		/// <summary>
		/// Char
		/// Description for Altinoren.ActiveWriter.NHibernateType.Char
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Char.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Char,
		/// <summary>
		/// DateTime
		/// Description for Altinoren.ActiveWriter.NHibernateType.DateTime
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/DateTime.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		DateTime,
		/// <summary>
		/// Decimal
		/// Description for Altinoren.ActiveWriter.NHibernateType.Decimal
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Decimal.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Decimal,
		/// <summary>
		/// Double
		/// Description for Altinoren.ActiveWriter.NHibernateType.Double
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Double.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Double,
		/// <summary>
		/// Guid
		/// Description for Altinoren.ActiveWriter.NHibernateType.Guid
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Guid.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Guid,
		/// <summary>
		/// Int16
		/// Description for Altinoren.ActiveWriter.NHibernateType.Int16
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Int16.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Int16,
		/// <summary>
		/// Int32
		/// Description for Altinoren.ActiveWriter.NHibernateType.Int32
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Int32.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Int32,
		/// <summary>
		/// Int64
		/// Description for Altinoren.ActiveWriter.NHibernateType.Int64
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Int64.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Int64,
		/// <summary>
		/// Ticks
		/// Description for Altinoren.ActiveWriter.NHibernateType.Ticks
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Ticks.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Ticks,
		/// <summary>
		/// TimeSpan
		/// Description for Altinoren.ActiveWriter.NHibernateType.TimeSpan
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/TimeSpan.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		TimeSpan,
		/// <summary>
		/// Timestamp
		/// Description for Altinoren.ActiveWriter.NHibernateType.Timestamp
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Timestamp.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Timestamp,
		/// <summary>
		/// TrueFalse
		/// Description for Altinoren.ActiveWriter.NHibernateType.TrueFalse
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/TrueFalse.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		TrueFalse,
		/// <summary>
		/// YesNo
		/// Description for Altinoren.ActiveWriter.NHibernateType.YesNo
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/YesNo.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		YesNo,
		/// <summary>
		/// Custom
		/// Description for Altinoren.ActiveWriter.NHibernateType.Custom
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NHibernateType/Custom.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Custom,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: Accessor
	/// Description for Altinoren.ActiveWriter.Accessor
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Accessor
	{
		/// <summary>
		/// Public
		/// Description for Altinoren.ActiveWriter.Accessor.Public
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.Accessor/Public.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Public,
		/// <summary>
		/// Private
		/// Description for Altinoren.ActiveWriter.Accessor.Private
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.Accessor/Private.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Private,
		/// <summary>
		/// Protected
		/// Description for Altinoren.ActiveWriter.Accessor.Protected
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.Accessor/Protected.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Protected,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: PropertyType
	/// Description for Altinoren.ActiveWriter.PropertyType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PropertyType
	{
		/// <summary>
		/// Property
		/// Description for Altinoren.ActiveWriter.PropertyType.Property
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyType/Property.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Property,
		/// <summary>
		/// Field
		/// Description for Altinoren.ActiveWriter.PropertyType.Field
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyType/Field.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Field,
		/// <summary>
		/// Version
		/// Description for Altinoren.ActiveWriter.PropertyType.Version
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyType/Version.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Version,
		/// <summary>
		/// Timestamp
		/// Description for Altinoren.ActiveWriter.PropertyType.Timestamp
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.PropertyType/Timestamp.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Timestamp,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: FieldCase
	/// Description for Altinoren.ActiveWriter.FieldCase
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FieldCase
	{
		/// <summary>
		/// Unchanged
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/Unchanged.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Unchanged,
		/// <summary>
		/// Camelcase
		/// Description for Altinoren.ActiveWriter.FieldCase.Camelcase
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/Camelcase.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Camelcase,
		/// <summary>
		/// CamelcaseUnderscore
		/// Description for Altinoren.ActiveWriter.FieldCase.CamelcaseUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/CamelcaseUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		CamelcaseUnderscore,
		/// <summary>
		/// CamelcaseMUnderscore
		/// Description for Altinoren.ActiveWriter.FieldCase.CamelcaseMUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/CamelcaseMUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		CamelcaseMUnderscore,
		/// <summary>
		/// Pascalcase
		/// Description for Altinoren.ActiveWriter.FieldCase.Pascalcase
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/Pascalcase.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Pascalcase,
		/// <summary>
		/// PascalcaseUnderscore
		/// Description for Altinoren.ActiveWriter.FieldCase.PascalcaseUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/PascalcaseUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		PascalcaseUnderscore,
		/// <summary>
		/// PascalcaseMUnderscore
		/// Description for Altinoren.ActiveWriter.FieldCase.PascalcaseMUnderscore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FieldCase/PascalcaseMUnderscore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		PascalcaseMUnderscore,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: CodeLanguage
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum CodeLanguage
	{
		/// <summary>
		/// CSharp
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CodeLanguage/CSharp.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		CSharp,
		/// <summary>
		/// VB
		/// Description for Altinoren.ActiveWriter.CodeLanguage.VB
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CodeLanguage/VB.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		VB,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: NullableUsage
	/// Description for Altinoren.ActiveWriter.NullableUsage
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum NullableUsage
	{
		/// <summary>
		/// No
		/// Description for Altinoren.ActiveWriter.NullableUsage.No
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NullableUsage/No.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		No,
		/// <summary>
		/// Native
		/// Description for Altinoren.ActiveWriter.NullableUsage.Native
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NullableUsage/Native.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Native,
		/// <summary>
		/// WithHelperLibrary
		/// Description for Altinoren.ActiveWriter.NullableUsage.WithHelperLibrary
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NullableUsage/WithHelperLibrary.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		WithHelperLibrary,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: Polymorphism
	/// Description for Altinoren.ActiveWriter.Polymorphism
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Polymorphism
	{
		/// <summary>
		/// Implicit
		/// Description for Altinoren.ActiveWriter.Polymorphism.Implicit
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.Polymorphism/Implicit.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Implicit,
		/// <summary>
		/// Explicit
		/// Description for Altinoren.ActiveWriter.Polymorphism.Explicit
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.Polymorphism/Explicit.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Explicit,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: OptimisticLocking
	/// Description for Altinoren.ActiveWriter.OptimisticLocking
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum OptimisticLocking
	{
		/// <summary>
		/// None
		/// Description for Altinoren.ActiveWriter.OptimisticLocking.None
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OptimisticLocking/None.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		None,
		/// <summary>
		/// Version
		/// Description for Altinoren.ActiveWriter.OptimisticLocking.Version
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OptimisticLocking/Version.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Version,
		/// <summary>
		/// Dirty
		/// Description for Altinoren.ActiveWriter.OptimisticLocking.Dirty
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OptimisticLocking/Dirty.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Dirty,
		/// <summary>
		/// All
		/// Description for Altinoren.ActiveWriter.OptimisticLocking.All
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.OptimisticLocking/All.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		All,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: NotFoundBehaviour
	/// Description for Altinoren.ActiveWriter.NotFoundBehaviour
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum NotFoundBehaviour
	{
		/// <summary>
		/// Default
		/// Description for Altinoren.ActiveWriter.NotFoundBehaviour.Default
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NotFoundBehaviour/Default.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Default,
		/// <summary>
		/// Exception
		/// Description for Altinoren.ActiveWriter.NotFoundBehaviour.Exception
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NotFoundBehaviour/Exception.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Exception,
		/// <summary>
		/// Ignore
		/// Description for Altinoren.ActiveWriter.NotFoundBehaviour.Ignore
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.NotFoundBehaviour/Ignore.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Ignore,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: CodeGenerationTarget
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum CodeGenerationTarget
	{
		/// <summary>
		/// ActiveRecord
		/// Description for Altinoren.ActiveWriter.CodeGenerationTarget.ActiveRecord
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CodeGenerationTarget/ActiveRecord.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		ActiveRecord,
		/// <summary>
		/// NHibernate
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.CodeGenerationTarget/NHibernate.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		NHibernate,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: ManyRelationCascadeEnum
	/// Description for Altinoren.ActiveWriter.ManyRelationCascadeEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum ManyRelationCascadeEnum
	{
		/// <summary>
		/// None
		/// Description for Altinoren.ActiveWriter.ManyRelationCascadeEnum.None
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.ManyRelationCascadeEnum/None.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		None,
		/// <summary>
		/// All
		/// Description for Altinoren.ActiveWriter.ManyRelationCascadeEnum.All
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.ManyRelationCascadeEnum/All.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		All,
		/// <summary>
		/// SaveUpdate
		/// Description for Altinoren.ActiveWriter.ManyRelationCascadeEnum.SaveUpdate
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.ManyRelationCascadeEnum/SaveUpdate.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		SaveUpdate,
		/// <summary>
		/// Delete
		/// Description for Altinoren.ActiveWriter.ManyRelationCascadeEnum.Delete
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.ManyRelationCascadeEnum/Delete.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Delete,
		/// <summary>
		/// AllDeleteOrphan
		/// Description for Altinoren.ActiveWriter.ManyRelationCascadeEnum.AllDeleteOrphan
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.ManyRelationCascadeEnum/AllDeleteOrphan.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		AllDeleteOrphan,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: InheritableBoolean
	/// Description for Altinoren.ActiveWriter.InheritableBoolean
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum InheritableBoolean
	{
		/// <summary>
		/// True
		/// Description for Altinoren.ActiveWriter.InheritableBoolean.True
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.InheritableBoolean/True.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		True,
		/// <summary>
		/// Inherit
		/// Description for Altinoren.ActiveWriter.InheritableBoolean.Inherit
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.InheritableBoolean/Inherit.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Inherit,
		/// <summary>
		/// False
		/// Description for Altinoren.ActiveWriter.InheritableBoolean.False
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.InheritableBoolean/False.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		False,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: FetchEnum
	/// Description for Altinoren.ActiveWriter.FetchEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FetchEnum
	{
		/// <summary>
		/// Select
		/// Description for Altinoren.ActiveWriter.FetchEnum.Select
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FetchEnum/Select.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Select,
		/// <summary>
		/// Join
		/// Description for Altinoren.ActiveWriter.FetchEnum.Join
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FetchEnum/Join.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Join,
		/// <summary>
		/// SubSelect
		/// Description for Altinoren.ActiveWriter.FetchEnum.SubSelect
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FetchEnum/SubSelect.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		SubSelect,
		/// <summary>
		/// Unspecified
		/// Description for Altinoren.ActiveWriter.FetchEnum.Unspecified
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.FetchEnum/Unspecified.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		Unspecified,
	}
}
namespace Altinoren.ActiveWriter
{
	/// <summary>
	/// DomainEnumeration: MetaDataGeneration
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum MetaDataGeneration
	{
		/// <summary>
		/// False
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.MetaDataGeneration/False.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		False,
		/// <summary>
		/// InClass
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.MetaDataGeneration/InClass.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		InClass,
		/// <summary>
		/// InSubClass
		/// </summary>
		[DslDesign::DescriptionResource("Altinoren.ActiveWriter.MetaDataGeneration/InSubClass.Description", typeof(global::Altinoren.ActiveWriter.ActiveWriterDomainModel), "Altinoren.ActiveWriter.GeneratedCode.DomainModelResx")]
		InSubClass,
	}
}

