//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debugging {
    using System;
    using System.Collections.Generic;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Blogs", Schema="dbo")]
    public partial class Blog : ActiveRecordBase<Blog> {
        
        private string _blog_name;
        
        private int _blog_id;
        
        private IList<Post> _posts;
        
        [Property("blog_name", ColumnType="String")]
        public string blog_name {
            get {
                return this._blog_name;
            }
            set {
                this._blog_name = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "blog_id", ColumnType="Int32")]
        public int blog_id {
            get {
                return this._blog_id;
            }
            set {
                this._blog_id = value;
            }
        }
        
        [HasMany(typeof(Post), ColumnKey="post_blogid", Table="Posts")]
        public IList<Post> Posts {
            get {
                return this._posts;
            }
            set {
                this._posts = value;
            }
        }
    }
    
    [ActiveRecord("Posts", Schema="dbo")]
    public partial class Post : ActiveRecordBase<Post> {
        
        private string _post_title;
        
        private string _post_contents;
        
        private string _post_category;
        
        private System.DateTime _post_created;
        
        private bool _post_published;
        
        private int _post_id;
        
        private Blog _blog;
        
        [Property("post_title", ColumnType="String")]
        public string post_title {
            get {
                return this._post_title;
            }
            set {
                this._post_title = value;
            }
        }
        
        [Property("post_contents", ColumnType="StringClob")]
        public string post_contents {
            get {
                return this._post_contents;
            }
            set {
                this._post_contents = value;
            }
        }
        
        [Property("post_category", ColumnType="String")]
        public string post_category {
            get {
                return this._post_category;
            }
            set {
                this._post_category = value;
            }
        }
        
        [Property("post_created", ColumnType="Timestamp")]
        public System.DateTime post_created {
            get {
                return this._post_created;
            }
            set {
                this._post_created = value;
            }
        }
        
        [Property("post_published", ColumnType="Boolean")]
        public bool post_published {
            get {
                return this._post_published;
            }
            set {
                this._post_published = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "post_id", ColumnType="Int32")]
        public int post_id {
            get {
                return this._post_id;
            }
            set {
                this._post_id = value;
            }
        }
        
        [BelongsTo("post_blogid", NotNull=false)]
        public Blog Blog {
            get {
                return this._blog;
            }
            set {
                this._blog = value;
            }
        }
    }
}
