//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.Components.Localization.MonoRail.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2008 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Date {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Date() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("Castle.Components.Localization.MonoRail.Resources.Date", typeof(Date).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'In {0} day{1}'.
        /// </summary>
        public static string InXDays {
            get {
                return ResourceManager.GetString("InXDays", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'In {0} hour{1}'.
        /// </summary>
        public static string InXHours {
            get {
                return ResourceManager.GetString("InXHours", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'In {0} minute{1}'.
        /// </summary>
        public static string InXMinutes {
            get {
                return ResourceManager.GetString("InXMinutes", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'In {0} month{1}'.
        /// </summary>
        public static string InXMonths {
            get {
                return ResourceManager.GetString("InXMonths", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'In {0} second{1}'.
        /// </summary>
        public static string InXSeconds {
            get {
                return ResourceManager.GetString("InXSeconds", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Just now'.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Today'.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tomorrow'.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} day{1} ago'.
        /// </summary>
        public static string XDaysAgo {
            get {
                return ResourceManager.GetString("XDaysAgo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} hour{1} ago'.
        /// </summary>
        public static string XHoursAgo {
            get {
                return ResourceManager.GetString("XHoursAgo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} minute{1} ago'.
        /// </summary>
        public static string XMinutesAgo {
            get {
                return ResourceManager.GetString("XMinutesAgo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} month{1} ago'.
        /// </summary>
        public static string XMonthsAgo {
            get {
                return ResourceManager.GetString("XMonthsAgo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} second{1} ago'.
        /// </summary>
        public static string XSecondsAgo {
            get {
                return ResourceManager.GetString("XSecondsAgo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Yesterday'.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'In {0} day{1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string InXDaysFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, InXDays, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'In {0} hour{1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string InXHoursFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, InXHours, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'In {0} minute{1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string InXMinutesFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, InXMinutes, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'In {0} month{1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string InXMonthsFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, InXMonths, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'In {0} second{1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string InXSecondsFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, InXSeconds, arg0, arg1);
        }
        
        /// <summary>
        /// The stub formatting method returning the JustNow property value.
        /// </summary>
        /// <returns>The JustNow property value.</returns>
        public static string JustNowFormat() {
            return JustNow;
        }
        
        /// <summary>
        /// The stub formatting method returning the Today property value.
        /// </summary>
        /// <returns>The Today property value.</returns>
        public static string TodayFormat() {
            return Today;
        }
        
        /// <summary>
        /// The stub formatting method returning the Tomorrow property value.
        /// </summary>
        /// <returns>The Tomorrow property value.</returns>
        public static string TomorrowFormat() {
            return Tomorrow;
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} day{1} ago'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string XDaysAgoFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, XDaysAgo, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} hour{1} ago'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string XHoursAgoFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, XHoursAgo, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} minute{1} ago'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string XMinutesAgoFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, XMinutesAgo, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} month{1} ago'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string XMonthsAgoFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, XMonthsAgo, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} second{1} ago'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string XSecondsAgoFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, XSecondsAgo, arg0, arg1);
        }
        
        /// <summary>
        /// The stub formatting method returning the Yesterday property value.
        /// </summary>
        /// <returns>The Yesterday property value.</returns>
        public static string YesterdayFormat() {
            return Yesterday;
        }
    }
}
