//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.Components.Localization.MonoRail.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2008 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Flags {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flags() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("Castle.Components.Localization.MonoRail.Resources.Flags", typeof(Flags).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a resource 'is'.
        /// </summary>
        public static System.Drawing.Bitmap _is {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("is", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'af'.
        /// </summary>
        public static System.Drawing.Bitmap af {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("af", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ar'.
        /// </summary>
        public static System.Drawing.Bitmap ar {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ar", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'az'.
        /// </summary>
        public static System.Drawing.Bitmap az {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("az", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'be'.
        /// </summary>
        public static System.Drawing.Bitmap be {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("be", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'bg'.
        /// </summary>
        public static System.Drawing.Bitmap bg {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("bg", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ca'.
        /// </summary>
        public static System.Drawing.Bitmap ca {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ca", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'cs'.
        /// </summary>
        public static System.Drawing.Bitmap cs {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("cs", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'da'.
        /// </summary>
        public static System.Drawing.Bitmap da {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("da", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'de'.
        /// </summary>
        public static System.Drawing.Bitmap de {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("de", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'dv'.
        /// </summary>
        public static System.Drawing.Bitmap dv {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("dv", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'el'.
        /// </summary>
        public static System.Drawing.Bitmap el {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("el", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'en'.
        /// </summary>
        public static System.Drawing.Bitmap en {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("en", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'es'.
        /// </summary>
        public static System.Drawing.Bitmap es {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("es", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'et'.
        /// </summary>
        public static System.Drawing.Bitmap et {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("et", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'eu'.
        /// </summary>
        public static System.Drawing.Bitmap eu {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("eu", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'fa'.
        /// </summary>
        public static System.Drawing.Bitmap fa {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("fa", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'fi'.
        /// </summary>
        public static System.Drawing.Bitmap fi {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("fi", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'fo'.
        /// </summary>
        public static System.Drawing.Bitmap fo {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("fo", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'fr'.
        /// </summary>
        public static System.Drawing.Bitmap fr {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("fr", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'gl'.
        /// </summary>
        public static System.Drawing.Bitmap gl {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("gl", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'gu'.
        /// </summary>
        public static System.Drawing.Bitmap gu {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("gu", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'he'.
        /// </summary>
        public static System.Drawing.Bitmap he {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("he", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'hi'.
        /// </summary>
        public static System.Drawing.Bitmap hi {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("hi", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'hr'.
        /// </summary>
        public static System.Drawing.Bitmap hr {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("hr", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'hu'.
        /// </summary>
        public static System.Drawing.Bitmap hu {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("hu", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'hy'.
        /// </summary>
        public static System.Drawing.Bitmap hy {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("hy", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'id'.
        /// </summary>
        public static System.Drawing.Bitmap id {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("id", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'it'.
        /// </summary>
        public static System.Drawing.Bitmap it {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("it", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ja'.
        /// </summary>
        public static System.Drawing.Bitmap ja {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ja", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ka'.
        /// </summary>
        public static System.Drawing.Bitmap ka {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ka", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'kk'.
        /// </summary>
        public static System.Drawing.Bitmap kk {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("kk", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'kn'.
        /// </summary>
        public static System.Drawing.Bitmap kn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("kn", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ko'.
        /// </summary>
        public static System.Drawing.Bitmap ko {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ko", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'kok'.
        /// </summary>
        public static System.Drawing.Bitmap kok {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("kok", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ky'.
        /// </summary>
        public static System.Drawing.Bitmap ky {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ky", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'lt'.
        /// </summary>
        public static System.Drawing.Bitmap lt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("lt", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'lv'.
        /// </summary>
        public static System.Drawing.Bitmap lv {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("lv", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'mk'.
        /// </summary>
        public static System.Drawing.Bitmap mk {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("mk", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'mn'.
        /// </summary>
        public static System.Drawing.Bitmap mn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("mn", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'mr'.
        /// </summary>
        public static System.Drawing.Bitmap mr {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("mr", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ms'.
        /// </summary>
        public static System.Drawing.Bitmap ms {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ms", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'nl'.
        /// </summary>
        public static System.Drawing.Bitmap nl {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("nl", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'no'.
        /// </summary>
        public static System.Drawing.Bitmap no {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("no", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'pa'.
        /// </summary>
        public static System.Drawing.Bitmap pa {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("pa", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'pl'.
        /// </summary>
        public static System.Drawing.Bitmap pl {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("pl", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'pt'.
        /// </summary>
        public static System.Drawing.Bitmap pt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("pt", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ro'.
        /// </summary>
        public static System.Drawing.Bitmap ro {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ro", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ru'.
        /// </summary>
        public static System.Drawing.Bitmap ru {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ru", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sa'.
        /// </summary>
        public static System.Drawing.Bitmap sa {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sa", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sk'.
        /// </summary>
        public static System.Drawing.Bitmap sk {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sk", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sl'.
        /// </summary>
        public static System.Drawing.Bitmap sl {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sl", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sq'.
        /// </summary>
        public static System.Drawing.Bitmap sq {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sq", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sr'.
        /// </summary>
        public static System.Drawing.Bitmap sr {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sr", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sv'.
        /// </summary>
        public static System.Drawing.Bitmap sv {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sv", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'sw'.
        /// </summary>
        public static System.Drawing.Bitmap sw {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sw", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'syr'.
        /// </summary>
        public static System.Drawing.Bitmap syr {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syr", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ta'.
        /// </summary>
        public static System.Drawing.Bitmap ta {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ta", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'te'.
        /// </summary>
        public static System.Drawing.Bitmap te {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("te", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'th'.
        /// </summary>
        public static System.Drawing.Bitmap th {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("th", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'tr'.
        /// </summary>
        public static System.Drawing.Bitmap tr {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("tr", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'tt'.
        /// </summary>
        public static System.Drawing.Bitmap tt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("tt", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'uk'.
        /// </summary>
        public static System.Drawing.Bitmap uk {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("uk", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'ur'.
        /// </summary>
        public static System.Drawing.Bitmap ur {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ur", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'uz'.
        /// </summary>
        public static System.Drawing.Bitmap uz {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("uz", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'vi'.
        /// </summary>
        public static System.Drawing.Bitmap vi {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("vi", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'zh-CHS'.
        /// </summary>
        public static System.Drawing.Bitmap zh_CHS {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("zh-CHS", _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'zh-CHT'.
        /// </summary>
        public static System.Drawing.Bitmap zh_CHT {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("zh-CHT", _resourceCulture)));
            }
        }
    }
}
