// Copyright 2004-2010 Castle Project - http://www.castleproject.org/
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Castle.ActiveWriter
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using DslModeling = Microsoft.VisualStudio.Modeling;

    public partial class Model
    {
        List<Import> additionalImportsPropertyStorage = new List<Import>();

        private List<Import> GetAdditionalImportsValue()
        {
            return this.additionalImportsPropertyStorage;
        }

        private void SetAdditionalImportsValue(List<Import> value)
        {
            this.additionalImportsPropertyStorage = value;
        }
    }

    [Serializable]
    [DefaultProperty("Name")]
    public class Import
    {
        [CategoryAttribute("Import")]
        [Description("Enter the namespace to be imported in the generated code.")]
        public string Name { get; set; }

        [CategoryAttribute("Import")]
        [Description("Enter the namespace generated by default to be replaced by this import (ex: System.Collections.Generic). This import will replace any previous one with the given name.")]
        public string Replaces { get; set; }
    }
}
