//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.Components.Localization.Tests.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2008 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MyResources2 {

		#region Static Variables 

        private static object _internalSyncObject;

		#endregion Static Variables 

		#region Properties 

        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to 'The first value'.
        /// </summary>
        public static string MyNamedEnumeration_Value1 {
            get {
                return ResourceManager.GetString("MyNamedEnumeration_Value1", _resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to 'The second value'.
        /// </summary>
        public static string MyNamedEnumeration_Value2 {
            get {
                return ResourceManager.GetString("MyNamedEnumeration_Value2", _resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to 'The third value'.
        /// </summary>
        public static string MyNamedEnumeration_Value3 {
            get {
                return ResourceManager.GetString("MyNamedEnumeration_Value3", _resourceCulture);
            }
        }

		#endregion Properties 

		#region Constructors 

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources2() {
        }

		#endregion Constructors 

		#region Public Methods 

        /// <summary>
        /// The stub formatting method returning the MyNamedEnumeration_Value1 property value.
        /// </summary>
        /// <returns>The MyNamedEnumeration_Value1 property value.</returns>
        public static string MyNamedEnumeration_Value1Format() {
            return MyNamedEnumeration_Value1;
        }

        /// <summary>
        /// The stub formatting method returning the MyNamedEnumeration_Value2 property value.
        /// </summary>
        /// <returns>The MyNamedEnumeration_Value2 property value.</returns>
        public static string MyNamedEnumeration_Value2Format() {
            return MyNamedEnumeration_Value2;
        }

        /// <summary>
        /// The stub formatting method returning the MyNamedEnumeration_Value3 property value.
        /// </summary>
        /// <returns>The MyNamedEnumeration_Value3 property value.</returns>
        public static string MyNamedEnumeration_Value3Format() {
            return MyNamedEnumeration_Value3;
        }

		#endregion Public Methods 
        private static global::System.Resources.ResourceManager _resourceManager;
        private static global::System.Globalization.CultureInfo _resourceCulture;
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("Castle.Components.Localization.Tests.Resources.MyResources2", typeof(MyResources2).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }

    }
}
